scrape_configs:
  - job_name: grafana
    scrape_interval: 3s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'node_exporter'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'node_exporter:9100' ]
  - job_name: 'postgres_exporter'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
  - job_name: application
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']