scrape_configs:
  - job_name: grafana
    scrape_interval: 3s
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: my-http-service
    scrape_interval: 3s
    static_configs:
      - targets: ['http-service:8080']
  
  - job_name: 'node_exporter'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'node_exporter:9100' ]